name: Testing

on:
  push:
  pull_request:

jobs:
  testing:
    # reuse workflow definitions
    uses: xonsh/actions/.github/workflows/test-poetry-xontrib.yml@main
    with:
      cache-dependency-path: pyproject.toml
      xontrib_name: openai
